name: Release Workflow
on: workflow_dispatch

jobs:
  release:
    name: Release to PowerShell Gallery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
          modulePath: /github/workspace/CyberwatchApi
